version: "3.2"
services:
  sender:
    image: claytonsilva/rabbitmq-go-service:latest
    container_name: sender
    networks:
      - rabbitmq_go_net
    links:
      - rabbitmq
    environment:
      - AMPQ_QUERYSTRING=amqp://guest:guest@rabbitmq:5672
      - QUEUE_NAME=queue-golang
      - INTERVAL=1000
      - CMD=send
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    # volumes:
    #   - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #   - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
